# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DgWaifgtG2N7UQ-DLZ12XIWTmaHgAcA
"""

# 1
print(" Tính toán a và b ")

a = float(input("Nhập a: "))
b = float(input("Nhập b: "))

tong = a + b
hieu = a - b
tich = a * b

if b != 0:
    thuong = a / b
else:
    thuong = "Không thể chia cho 0"

print("Tổng:", tong)
print("Hiệu:", hieu)
print("Tích:", tich)
print("Thương:", thuong)


# 2

print("\n Lấy chuỗi con ")

chuoi = "Hello World"
ket_qua = chuoi[2:5]

print("Chuỗi ban đầu:", chuoi)
print("Kết quả (index 2 đến 4):", ket_qua)


# 3

print("\n Xử lý chuỗi ")

chuoi2 = "   Hello World  "

chuoi_trim = chuoi2.strip()
chuoi_upper = chuoi_trim.upper()
chuoi_lower = chuoi_trim.lower()
chuoi_replace = chuoi_trim.replace("H", "J")

print("Chuỗi ban đầu:", chuoi2)
print("Sau khi xóa khoảng trắng:", chuoi_trim)
print("Chữ hoa:", chuoi_upper)
print("Chữ thường:", chuoi_lower)
print("Thay H -> J:", chuoi_replace)

a = 10
b = 5
c = 5
d = 10

# 4. In ra "Hello World!" nếu a lớn hơn b
if a > b:
    print("Hello World!")

# 5. In ra "Yes" nếu a bằng b, ngược lại in "No"
if a == b:
    print("Yes")
else:
    print("No")

# 6. In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại (a < b)
if a == b:
    print(1)
elif a > b:
    print(2)
else:
    print(3)

# 7. In ra "Hello World!" nếu a bằng b VÀ b bằng d
if a == b and b == d:
    print("Hello World!")

# 8. In ra "Hello World!" nếu a bằng b HOẶC c bằng d
if a == b or c == d:
    print("Hello World!")

# 9. Viết lại câu lệnh if...else lên cùng 1 dòng
print("Yes") if a > b else print("No")

# 10. Nhập vào 2 số a, b. Thực hiện câu lệnh và cho biết kết quả
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))

print("A") if a > b else print("=") if a == b else print("B")

# 11. Tạo mảng b chứa các phần tử chẵn của a
n = int(input("Nhập n: "))
a = [int(input(f"a[{i}]: ")) for i in range(n)]
b = [x for x in a if x % 2 == 0]
print("Mảng b chẵn:", b)

# 12.
tong_12 = sum(x for x in range(1000) if x % 3 == 0 or x % 5 == 0)
print("Tổng bội 3 hoặc 5:", tong_12)

# 13. Trộn 2 mảng
def tron_mang(mang_a, mang_b):
    res = []
    len_min = min(len(mang_a), len(mang_b))
    for i in range(len_min):
        res.append(mang_a[i] + mang_b[i])
    res.extend(mang_a[len_min:] if len(mang_a) > len(mang_b) else mang_b[len_min:])
    return res

print("Kết quả trộn:", tron_mang([3, 9, 1, 4], [2, 7, 4, 3, 2, 8]))

#14 Cho mảng 2 chiều a có m dòng, n cột chứa số nguyên
import random

# a. Tạo mảng ngẫu nhiên
m, n = 3, 4 # ví dụ m dòng n cột
matrix = [[random.randint(1, 100) for _ in range(n)] for _ in range(m)]

# b. Xuất dòng k
k = 1
print(f"Dòng {k}:", matrix[k])

# c. Xuất cột k
print(f"Cột {k}:", [row[k] for row in matrix])

# e. Tìm cột có tích nhỏ nhất
def tich_cot(mat, col_idx):
    res = 1
    for row in mat: res *= row[col_idx]
    return res

min_tich = min(range(n), key=lambda c: tich_cot(matrix, c))
print(f"Cột có tích nhỏ nhất là cột: {min_tich}")

# g. Trung bình cộng phần tử chẵn thuộc dòng lẻ (dòng 1, 3, 5...)
ds_chan_dong_le = [x for r_idx, row in enumerate(matrix) if r_idx % 2 != 0 for x in row if x % 2 == 0]
tbc = sum(ds_chan_dong_le) / len(ds_chan_dong_le) if ds_chan_dong_le else 0

# a. Xây dựng cấu trúc SINHVIEN
class SinhVien:
    def __init__(self, mssv, ten, nam_sinh, dtb):
        self.mssv = str(mssv).strip()
        self.ten = str(ten).strip()
        self.nam_sinh = int(nam_sinh)
        self.dtb = float(dtb)

# b. Tạo danh sách sinh viên mẫu
danh_sach_sv = [
    SinhVien("01DH0001", "Phan Anh Lan", 2004, 7.5),
    SinhVien("02DH0002", "Nguyen Lan", 2006, 4.5),
    SinhVien("03CD0001", "Phan Van Tu", 2002, 8.0),
    SinhVien("04DH0005", "Tran Thi Lan", 2006, 9.0)
]

# c. Đếm sinh viên đủ điều kiện lên lớp (DTB >= 5)
def sv_len_lop(ds):
    res = [sv for sv in ds if sv.dtb >= 5]
    return len(res)

# d. Xuất sinh viên đủ 20 tuổi (Tính theo năm hiện tại 2026)
def xuat_sv_20_tuoi(ds):
    nam_hien_tai = 2026
    found = False
    print("--- Danh sách sinh viên đủ 20 tuổi ---")
    for sv in ds:
        if nam_hien_tai - sv.nam_sinh == 20:
            print(f"- {sv.ten} ({sv.nam_sinh})")
            found = True
    if not found: print("Không có sinh viên nào 20 tuổi.")

# e. Đếm sinh viên hệ đại học (Ký tự 2,3 là 'DH' -> index 1,2)
def dem_sv_dai_hoc(ds):
    count = 0
    for sv in ds:
        # Dùng .upper() để so sánh chính xác hơn
        if len(sv.mssv) >= 3 and sv.mssv[1:3].upper() == "DH":
            count += 1
    return count

# f. Đếm sinh viên có tên "Lan"
def dem_ten_lan(ds):
    count = 0
    for sv in ds:
        parts = sv.ten.split()
        if parts and parts[-1].lower() == "lan":
            count += 1
    return count

# g. Đếm sinh viên có họ "Phan"
def dem_ho_phan(ds):
    count = 0
    for sv in ds:
        parts = sv.ten.split()
        if parts and parts[0].lower() == "phan":
            count += 1
    return count

print(f"1. Số SV đủ điều kiện lên lớp: {sv_len_lop(danh_sach_sv)}")
print(f"2. Số SV hệ Đại học: {dem_sv_dai_hoc(danh_sach_sv)}")
print(f"3. Số SV tên 'Lan': {dem_ten_lan(danh_sach_sv)}")
print(f"4. Số SV họ 'Phan': {dem_ho_phan(danh_sach_sv)}")
xuat_sv_20_tuoi(danh_sach_sv)

# 1: TRỘN 2 MẢNG
def tron_mang(a, b):
    c = []
    min_len = min(len(a), len(b))

    # Lấy giá trị nhỏ hơn tại mỗi vị trí tương ứng
    for i in range(min_len):
        c.append(min(a[i], b[i]))

    # Ghép phần dư của mảng dài hơn vào sau
    if len(a) > len(b):
        c.extend(a[min_len:])
    else:
        c.extend(b[min_len:])

    return c


# BÀI 2: XỬ LÝ MA TRẬN

# a. Tổng tam giác trên chéo phụ (bao gồm cả đường chéo phụ)
def tong_tam_giac_tren_cheo_phu(a):
    n = len(a)
    tong = 0
    for i in range(n):
        for j in range(n):
            if i + j <= n - 1:
                tong += a[i][j]
    return tong


# b. Chuyển âm thành dương
def chuyen_am_thanh_duong(a):
    for i in range(len(a)):
        for j in range(len(a[i])):
            if a[i][j] < 0:
                a[i][j] = abs(a[i][j])
    return a


# c. Thay số chẵn bằng x
def thay_chan_bang_x(a, x):
    for i in range(len(a)):
        for j in range(len(a[i])):
            if a[i][j] % 2 == 0:
                a[i][j] = x
    return a


# d. Kiểm tra toàn chẵn
def toan_chan(a):
    for row in a:
        for x in row:
            if x % 2 != 0:
                return False
    return True


# e. Kiểm tra đối xứng (qua chéo chính)
def doi_xung(a):
    n = len(a)
    for i in range(n):
        for j in range(i + 1, n): # Chỉ cần kiểm tra một nửa tam giác
            if a[i][j] != a[j][i]:
                return False
    return True


# f. Chéo chính tăng dần
def cheo_chinh_tang(a):
    n = len(a)
    for i in range(n - 1):
        if a[i][i] >= a[i+1][i+1]:
            return False
    return True


# g. Các phần tử tam giác dưới chéo phụ
def tam_giac_duoi_cheo_phu(a):
    n = len(a)
    ket_qua = []
    for i in range(n):
        for j in range(n):
            if i + j >= n - 1:
                ket_qua.append(a[i][j])
    return ket_qua


# h. Chéo phụ giảm dần
def cheo_phu_giam(a):
    n = len(a)
    for i in range(n - 1):
        # Phần tử hiện tại: a[i][n-1-i]
        # Phần tử kế tiếp: a[i+1][n-2-i]
        if a[i][n - 1 - i] <= a[i + 1][n - 2 - i]:
            return False
    return True

# Hàm hỗ trợ in ma trận cho đẹp
def in_ma_tran(matran):
    for row in matran:
        print("\t", *row)


# --- MAIN ---

# --- Bài 1 ---
print("=== Bài 1: Trộn 2 mảng ===")
n_size = int(input("Nhập số phần tử mảng a: "))
a_list = list(map(int, input("Nhập mảng a: ").split()))

m_size = int(input("Nhập số phần tử mảng b: "))
b_list = list(map(int, input("Nhập mảng b: ").split()))

print("Mảng kết quả:", tron_mang(a_list, b_list))


# --- Bài 2 ---
print("\n=== Bài 2: Ma trận ===")
n = int(input("Nhập kích thước ma trận vuông n: "))

matrix = []
print("Nhập ma trận (từng dòng, các số cách nhau bởi dấu cách):")
for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)

# a
print(f"> Tổng tam giác trên chéo phụ: {tong_tam_giac_tren_cheo_phu(matrix)}")

# b
print("> Ma trận sau khi đổi âm -> dương:")
in_ma_tran(chuyen_am_thanh_duong([row[:] for row in matrix]))

# c
val_x = int(input("Nhập x để thay số chẵn: "))
print(f"> Ma trận sau khi thay số chẵn bằng {val_x}:")
in_ma_tran(thay_chan_bang_x([row[:] for row in matrix], val_x))

# d
print(f"> Ma trận toàn chẵn: {toan_chan(matrix)}")

# e
print(f"> Ma trận đối xứng: {doi_xung(matrix)}")

# f
print(f"> Chéo chính tăng dần: {cheo_chinh_tang(matrix)}")

# g
print(f"> Các phần tử tam giác dưới chéo phụ: {tam_giac_duoi_cheo_phu(matrix)}")

# h
print(f"> Chéo phụ giảm dần: {cheo_phu_giam(matrix)}")

import pandas as pd
import matplotlib.pyplot as plt

# 3: Dictionary chứa 3 Dictionaries ---
data_center = {
    "Web_Dev": {"language": "JavaScript", "level": "Easy", "duration": "3 months"},
    "Data_Sci": {"language": "Python", "level": "Hard", "duration": "6 months"},
    "Mobile_App": {"language": "Dart", "level": "Medium", "duration": "4 months"}
}
print("--- Câu 3: Nested Dictionary ---")
print(data_center["Data_Sci"])


# 4 đọc và xuất file
print("\n--- Câu 4: File Handling ---")
file_name = "hoc_tap.csv"


with open(file_name, "w", encoding="utf-8") as f:
    f.write("Mon,Diem,SoGioHoc\nPython,9.5,40\nC++,8.0,55\nSQL,8.5,30\nJava,7.0,45")
print(f"Đã tạo file {file_name} thành công.")

with open(file_name, "r") as f:
    print("Nội dung file:\n", f.read())


# 5 Pandas & Matplotli
print("\n--- Câu 5: Data Analysis ---")

df = pd.read_csv(file_name)
print("Dữ liệu dạng DataFrame:")
print(df)

plt.figure(figsize=(8, 5))
plt.bar(df['Mon'], df['Diem'], color='teal')
plt.title("Biểu đồ điểm số các môn học", fontsize=14)
plt.xlabel("Môn học")
plt.ylabel("Điểm")
plt.ylim(0, 10)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()